language: erlang

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c59e6bffa0b41a693676 # GsDevKit/chat (public)
    on_success: always # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

env:


#  - GS_VERSION=3.1.0.6 TEST=BasicTodeClient
#  - GS_VERSION=3.2.7   TEST=BasicTodeClient
  - GS_VERSION=3.1.0.6 TEST=Basic
  - GS_VERSION=3.2.7   TEST=Basic
#  - GS_VERSION=3.1.0.6 TEST=Projects1
#  - GS_VERSION=3.2.7   TEST=Projects1
#  - GS_VERSION=3.1.0.6 TEST=Projects2
#  - GS_VERSION=3.2.7   TEST=Projects2
#  - GS_VERSION=3.1.0.6 TEST=Magritte
#  - GS_VERSION=3.2.7   TEST=Magritte
#  - GS_VERSION=3.1.0.6 TEST=Pier300
##  - GS_VERSION=3.2.7   TEST=Pier300  # older versions of Seaside3.0 aren't loadable in 3.2 ... invalid UTF8 characters in WAXMLEncoder table
#  - GS_VERSION=3.1.0.6 TEST=Seaside3
#  - GS_VERSION=3.2.7   TEST=Seaside3
#  - GS_VERSION=3.1.0.6 TEST=Zinc
#  - GS_VERSION=3.2.7   TEST=Zinc

before_script:
  - export GS_HOME="$(pwd)"
  - export PATH=$GS_HOME/bin:$PATH
  - export GS_TRAVIS=true
  - sudo apt-get update -qq
  - sudo apt-get -y install libpam0g:i386
  - sudo ln -s /lib/i386-linux-gnu/libpam.so.0 /lib/libpam.so.0
  - sudo apt-get install -qq gcc-multilib libcurl3:i386 libstdc++6:i386
  - sudo ln -s /usr/lib/i386-linux-gnu/libstdc++.so.6 /usr/lib/i386-linux-gnu/libstdc++.so

script:
  - tests/testTravisCI.sh
