#! /bin/bash

#=========================================================================
# Copyright (c) 2014 GemTalk Systems, LLC <dhenrich@gemtalksystems.com>.
#
# Project load template script.
# 
#  1. Copy this file to the $GS_HOME/projects/<project=name> directory
#  2. Edit the following three shell variables as needed
#  3. Add additional args (for load options) and expand the usage() as needed
#  
#=========================================================================

projectName="ZincHTTPComponents"
projectLoadCommand="project load $projectName"
logFile="projectLoad_${projectName}.log"

projectLoadCommand="eval \`Transcript cr; show: 'hello'\`"

usage() {
  cat <<HELP
USAGE: $(basename $0) [-h] <stone-name>

Load $projectName into named stone.

OPTIONS
  -h show usage

EXAMPLES
  $(basename $0) -h
  $(basename $0) devkit

HELP
}

set -e # exit on error
if [ "${GS_HOME}x" = "x" ] ; then
  echo "the GS_HOME environment variable needs to be defined"; exit 1
fi
source ${GS_HOME}/bin/shFunctions

helpOpts

if [ $# -ne 1 ]; then
  usage; exit 0
fi
stoneName="$1"
$GS_HOME/bin/tode tode $stoneName 1> $GS_HOME/gemstone/stones/$stoneName/logs/$logFile << EOF
$projectLoadCommand
EOF
